[build]
  base = "frontend"
  command = "NODE_OPTIONS=--max-old-space-size=8192 npm run build"
  publish = "dist"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefer-offline --no-audit"

# ✅ JSON 캐시 방지
[[headers]]
  for = "/data/stocks/*.json"
  [headers.values]
    Cache-Control = "no-store"

# ✅ sitemap.xml 예외 먼저 설정
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

# ✅ MIME 타입 명시 (명확하게 XML로 인식되게)
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "no-store, no-cache, must-revalidate"

# ✅ 그 후 모든 SPA 리디렉션은 맨 아래
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
